import fs from 'node:fs';

const s = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const GEOM = 11, BS = 28, C0 = GEOM + BS; // contour starts after geometry + blendshapes
const r3 = (v) => Math.round(v * 1000) / 1000;

const T = [-1, -0.85, -0.6, -0.35, -0.15, 0, 0.15, 0.35, 0.6, 0.85, 1, 0.85, 0.6, 0.35, 0.15, 0, -0.15, -0.35, -0.6, -0.85];
const upperOuter = (t) => -0.13 * Math.pow(1 - t * t, 0.55) + 0.025 * Math.exp(-((t / 0.13) ** 2));
const lowerOuter = (t) => 0.15 * Math.pow(1 - t * t, 0.7);
const neutral = [];
T.forEach((t, i) => neutral.push([0.42 * t, i <= 10 ? upperOuter(t) : lowerOuter(t)]));
T.forEach((t, i) => neutral.push([0.35 * t, (i <= 10 ? -1 : 1) * 0.012 * (1 - t * t)]));

function frames(seq) {
  return seq.map((f) => neutral.map(([x, y], p) => [r3(x + f[C0 + 2 * p]), r3(y + f[C0 + 2 * p + 1])]));
}

function resample(arr, n) {
  return Array.from({ length: n }, (_, i) => {
    const x = (i * (arr.length - 1)) / (n - 1);
    const a = Math.floor(x), b = Math.min(arr.length - 1, a + 1);
    return r3(arr[a] + (arr[b] - arr[a]) * (x - a));
  });
}

const names = Object.fromEntries(s.phrases.map((p) => [p.id, p.ru]));
const pick = ['drink', 'doctor', 'turn', 'pain', 'family', 'breath'];
const fingerprints = pick.map((id) => ({
  id,
  text: names[id],
  takes: (s.templates[`${id}|ru`] || []).filter((q) => q.length >= 40).slice(0, 5).map((q) => resample(q.map((f) => f[1]), 64)),
}));

const heroSeq = s.templates['drink|ru'].find((q) => q.length >= 60);
const out = {
  hero: { text: names.drink, fps: 30, frames: frames(heroSeq) },
  fingerprints,
};
fs.writeFileSync(new URL('../landing-data.js', import.meta.url), `// Generated by tools/landing-data.mjs from a real calibration session.\nexport default ${JSON.stringify(out)};\n`);
console.log('hero frames', out.hero.frames.length, 'fingerprints', fingerprints.map((f) => `${f.id}:${f.takes.length}`).join(' '));
